version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
      versioning-strategy: increase
      groups:
          dependencies:
              applies-to: version-updates
              update-types:
                  - minor
                  - patch
              exclude-patterns:
                  - '*@dhis2*'
                  - '*i18next*'
          security:
              applies-to: security-updates
              update-types:
                  - minor
                  - patch
