import * as types from '../../constants/actionTypes.js'
import {
    addDimensionFilter,
    removeDimensionFilter,
    changeDimensionFilter,
    addFilter,
    removeFilter,
    changeFilter,
    setProgram,
    setProgramStage,
    setDataItem,
    setStyleDataItem,
    setOptionStyle,
    setBooleanStyle,
    setThematicMapType,
    setClassification,
    setColorScale,
    setLegendDecimalPlaces,
    setLegendIsolated,
    setEventStatus,
    setEventCoordinateField,
    setFallbackCoordinateField,
    setEventClustering,
    setCountFeaturesWithoutCoordinates,
    setCountEventsOutsideOrgUnits,
    setEventPointRadius,
    setEventPointColor,
    setRelatedPointColor,
    setRelatedPointRadius,
    setRelationshipLineColor,
    setOrganisationUnitGroupSet,
    setOrganisationUnitColor,
    setOrganisationUnitField,
    setPeriodName,
    setPeriodType,
    setPeriods,
    setStartDate,
    setEndDate,
    setBackupPeriodsDates,
    setAggregationType,
    setOrgUnits,
    setOrgUnitMode,
    setStyle,
    setFilter,
    setBand,
    setLabels,
    setLabelTemplate,
    setLabelFontSize,
    setLabelFontWeight,
    setLabelFontStyle,
    setLabelFontColor,
    setBufferRadius,
    setGeometryCentroid,
    setRadiusLow,
    setRadiusHigh,
    setLegendSet,
    setOrgUnitPath,
    setTrackedEntityType,
    setTrackedEntityRelationshipType,
    setTrackedEntityRelationshipOutsideProgram,
    setProgramStatus,
    setFollowUpStatus,
    setRenderingStrategy,
    setNoDataLegend,
    setUnclassifiedLegend,
    setEarthEnginePeriod,
    setFeatureStyle,
    setLabelDataItem,
} from '../layerEdit.js'

describe('layerEdit simple action creators', () => {
    it.each([
        {
            creator: addDimensionFilter,
            args: [{ dimension: 'ou' }],
            type: types.LAYER_EDIT_DIMENSION_FILTER_ADD,
            rest: { filter: { dimension: 'ou' } },
        },
        {
            creator: removeDimensionFilter,
            args: [1],
            type: types.LAYER_EDIT_DIMENSION_FILTER_REMOVE,
            rest: { index: 1 },
        },
        {
            creator: changeDimensionFilter,
            args: [1, { dimension: 'ou' }],
            type: types.LAYER_EDIT_DIMENSION_FILTER_CHANGE,
            rest: { index: 1, filter: { dimension: 'ou' } },
        },
        {
            creator: addFilter,
            args: [{ dimension: 'dx' }],
            type: types.LAYER_EDIT_FILTER_ADD,
            rest: { filter: { dimension: 'dx' } },
        },
        {
            creator: removeFilter,
            args: [2],
            type: types.LAYER_EDIT_FILTER_REMOVE,
            rest: { index: 2 },
        },
        {
            creator: changeFilter,
            args: [2, { dimension: 'dx' }],
            type: types.LAYER_EDIT_FILTER_CHANGE,
            rest: { index: 2, filter: { dimension: 'dx' } },
        },
        {
            creator: setProgram,
            args: [{ id: 'prog1' }],
            type: types.LAYER_EDIT_PROGRAM_SET,
            rest: { program: { id: 'prog1' } },
        },
        {
            creator: setProgramStage,
            args: [{ id: 'stage1' }],
            type: types.LAYER_EDIT_PROGRAM_STAGE_SET,
            rest: { programStage: { id: 'stage1' } },
        },
        {
            creator: setDataItem,
            args: [{ id: 'de1' }, 'columns'],
            type: types.LAYER_EDIT_DATA_ITEM_SET,
            rest: { dataItem: { id: 'de1' }, dimension: 'columns' },
        },
        {
            creator: setStyleDataItem,
            args: [{ id: 'de1' }],
            type: types.LAYER_EDIT_STYLE_DATA_ITEM_SET,
            rest: { dataItem: { id: 'de1' } },
        },
        {
            creator: setOptionStyle,
            args: [[{ code: 'A' }]],
            type: types.LAYER_EDIT_STYLE_DATA_ITEM_OPTIONS_SET,
            rest: { options: [{ code: 'A' }] },
        },
        {
            creator: setBooleanStyle,
            args: ['true', '#fff'],
            type: types.LAYER_EDIT_STYLE_DATA_ITEM_BOOLEAN_SET,
            rest: { value: 'true', color: '#fff' },
        },
        {
            creator: setThematicMapType,
            args: ['CHOROPLETH'],
            type: types.LAYER_EDIT_THEMATIC_MAP_TYPE_SET,
            rest: { payload: 'CHOROPLETH' },
        },
        {
            creator: setClassification,
            args: ['equalIntervals'],
            type: types.LAYER_EDIT_CLASSIFICATION_SET,
            rest: { method: 'equalIntervals' },
        },
        {
            creator: setColorScale,
            args: [['#fff', '#000']],
            type: types.LAYER_EDIT_COLOR_SCALE_SET,
            rest: { colorScale: ['#fff', '#000'] },
        },
        {
            creator: setLegendDecimalPlaces,
            args: [2],
            type: types.LAYER_EDIT_LEGEND_DECIMAL_PLACES_SET,
            rest: { legendDecimalPlaces: 2 },
        },
        {
            creator: setLegendIsolated,
            args: [true],
            type: types.LAYER_EDIT_LEGEND_ISOLATED_SET,
            rest: { legendIsolated: true },
        },
        {
            creator: setEventStatus,
            args: ['ACTIVE'],
            type: types.LAYER_EDIT_EVENT_STATUS_SET,
            rest: { status: 'ACTIVE' },
        },
        {
            creator: setEventCoordinateField,
            args: ['field1', 'COORDINATE'],
            type: types.LAYER_EDIT_EVENT_COORDINATE_FIELD_SET,
            rest: { fieldId: 'field1', fieldType: 'COORDINATE' },
        },
        {
            creator: setFallbackCoordinateField,
            args: ['field1'],
            type: types.LAYER_EDIT_FALLBACK_COORDINATE_FIELD_SET,
            rest: { fieldId: 'field1' },
        },
        {
            creator: setEventClustering,
            args: [true],
            type: types.LAYER_EDIT_EVENT_CLUSTERING_SET,
            rest: { checked: true },
        },
        {
            creator: setCountFeaturesWithoutCoordinates,
            args: [true],
            type: types.LAYER_EDIT_COUNT_FEATURES_WITHOUT_COORDS_SET,
            rest: { checked: true },
        },
        {
            creator: setCountEventsOutsideOrgUnits,
            args: [true],
            type: types.LAYER_EDIT_COUNT_EVENTS_OUTSIDE_OU_SET,
            rest: { checked: true },
        },
        {
            creator: setEventPointRadius,
            args: [5],
            type: types.LAYER_EDIT_EVENT_POINT_RADIUS_SET,
            rest: { radius: 5 },
        },
        {
            creator: setEventPointColor,
            args: ['#fff'],
            type: types.LAYER_EDIT_EVENT_POINT_COLOR_SET,
            rest: { color: '#fff' },
        },
        {
            creator: setRelatedPointColor,
            args: ['#fff'],
            type: types.LAYER_EDIT_RELATED_POINT_COLOR_SET,
            rest: { color: '#fff' },
        },
        {
            creator: setRelatedPointRadius,
            args: [5],
            type: types.LAYER_EDIT_RELATED_POINT_RADIUS_SET,
            rest: { radius: 5 },
        },
        {
            creator: setRelationshipLineColor,
            args: ['#fff'],
            type: types.LAYER_EDIT_RELATIONSHIP_LINE_COLOR_SET,
            rest: { color: '#fff' },
        },
        {
            creator: setOrganisationUnitGroupSet,
            args: [{ id: 'ougs1' }],
            type: types.LAYER_EDIT_ORGANISATION_UNIT_GROUP_SET,
            rest: { organisationUnitGroupSet: { id: 'ougs1' } },
        },
        {
            creator: setOrganisationUnitColor,
            args: ['#fff'],
            type: types.LAYER_EDIT_ORGANISATION_UNIT_COLOR_SET,
            rest: { color: '#fff' },
        },
        {
            creator: setOrganisationUnitField,
            args: [{ id: 'field1' }],
            type: types.LAYER_EDIT_ORGANISATION_UNIT_FIELD_SET,
            rest: { payload: { id: 'field1' } },
        },
        {
            creator: setPeriodName,
            args: ['Last year'],
            type: types.LAYER_EDIT_PERIOD_NAME_SET,
            rest: { periodName: 'Last year' },
        },
        {
            creator: setPeriodType,
            args: ['RELATIVE', true],
            type: types.LAYER_EDIT_PERIOD_TYPE_SET,
            rest: { periodType: 'RELATIVE', keepPeriod: true },
        },
        {
            creator: setPeriods,
            args: [[{ id: '2021' }]],
            type: types.LAYER_EDIT_PERIODS_SET,
            rest: { periods: [{ id: '2021' }] },
        },
        {
            creator: setStartDate,
            args: ['2021-01-01'],
            type: types.LAYER_EDIT_START_DATE_SET,
            rest: { startDate: '2021-01-01' },
        },
        {
            creator: setEndDate,
            args: ['2021-12-31'],
            type: types.LAYER_EDIT_END_DATE_SET,
            rest: { endDate: '2021-12-31' },
        },
        {
            creator: setBackupPeriodsDates,
            args: [{ periods: [] }],
            type: types.LAYER_EDIT_BACKUP_PERIODSDATES_SET,
            rest: { backupPeriodsDates: { periods: [] } },
        },
        {
            creator: setAggregationType,
            args: ['SUM'],
            type: types.LAYER_EDIT_AGGREGATION_TYPE_SET,
            rest: { aggregationType: 'SUM' },
        },
        {
            creator: setOrgUnits,
            args: [{ id: 'ou1' }],
            type: types.LAYER_EDIT_ORGANISATION_UNITS_SET,
            rest: { payload: { id: 'ou1' } },
        },
        {
            creator: setOrgUnitMode,
            args: ['SELECT'],
            type: types.LAYER_EDIT_ORGANISATION_UNIT_MODE_SET,
            rest: { payload: 'SELECT' },
        },
        {
            creator: setStyle,
            args: [{ color: '#fff' }],
            type: types.LAYER_EDIT_STYLE_SET,
            rest: { payload: { color: '#fff' } },
        },
        {
            creator: setFilter,
            args: ['NDVI > 0.5'],
            type: types.LAYER_EDIT_FILTER_SET,
            rest: { filter: 'NDVI > 0.5' },
        },
        {
            creator: setLabels,
            args: [true],
            type: types.LAYER_EDIT_LABELS_SET,
            rest: { isChecked: true },
        },
        {
            creator: setLabelTemplate,
            args: ['{name}'],
            type: types.LAYER_EDIT_LABEL_TEMPLATE,
            rest: { template: '{name}' },
        },
        {
            creator: setLabelFontSize,
            args: [12],
            type: types.LAYER_EDIT_LABEL_FONT_SIZE_SET,
            rest: { size: 12 },
        },
        {
            creator: setLabelFontWeight,
            args: ['bold'],
            type: types.LAYER_EDIT_LABEL_FONT_WEIGHT_SET,
            rest: { weight: 'bold' },
        },
        {
            creator: setLabelFontStyle,
            args: ['italic'],
            type: types.LAYER_EDIT_LABEL_FONT_STYLE_SET,
            rest: { style: 'italic' },
        },
        {
            creator: setLabelFontColor,
            args: ['#fff'],
            type: types.LAYER_EDIT_LABEL_FONT_COLOR_SET,
            rest: { color: '#fff' },
        },
        {
            creator: setBufferRadius,
            args: [500],
            type: types.LAYER_EDIT_BUFFER_RADIUS_SET,
            rest: { radius: 500 },
        },
        {
            creator: setGeometryCentroid,
            args: [true],
            type: types.LAYER_EDIT_GEOMETRY_CENTROIDS_SET,
            rest: { payload: true },
        },
        {
            creator: setRadiusLow,
            args: [2],
            type: types.LAYER_EDIT_RADIUS_LOW_SET,
            rest: { radius: 2 },
        },
        {
            creator: setRadiusHigh,
            args: [10],
            type: types.LAYER_EDIT_RADIUS_HIGH_SET,
            rest: { radius: 10 },
        },
        {
            creator: setLegendSet,
            args: [{ id: 'ls1' }],
            type: types.LAYER_EDIT_LEGEND_SET_SET,
            rest: { legendSet: { id: 'ls1' } },
        },
        {
            creator: setOrgUnitPath,
            args: ['ou1', '/root/ou1'],
            type: types.LAYER_EDIT_ORGANISATION_UNIT_PATH_SET,
            rest: { id: 'ou1', path: '/root/ou1' },
        },
        {
            creator: setTrackedEntityType,
            args: [{ id: 'tet1' }],
            type: types.LAYER_EDIT_TRACKED_ENTITY_TYPE_SET,
            rest: { trackedEntityType: { id: 'tet1' } },
        },
        {
            creator: setTrackedEntityRelationshipType,
            args: [{ id: 'rt1' }],
            type: types.LAYER_EDIT_TRACKED_ENTITY_RELATIONSHIP_TYPE_SET,
            rest: { relationshipType: { id: 'rt1' } },
        },
        {
            creator: setTrackedEntityRelationshipOutsideProgram,
            args: [true],
            type: types.LAYER_EDIT_TRACKED_ENTITY_RELATIONSHIP_OUTSIDE_PROGRAM_SET,
            rest: { payload: true },
        },
        {
            creator: setProgramStatus,
            args: ['ACTIVE'],
            type: types.LAYER_EDIT_PROGRAM_STATUS_SET,
            rest: { payload: 'ACTIVE' },
        },
        {
            creator: setFollowUpStatus,
            args: [true],
            type: types.LAYER_EDIT_FOLLOW_UP_SET,
            rest: { payload: true },
        },
        {
            creator: setRenderingStrategy,
            args: ['SINGLE'],
            type: types.LAYER_EDIT_RENDERING_STRATEGY_SET,
            rest: { payload: 'SINGLE' },
        },
        {
            creator: setNoDataLegend,
            args: [true],
            type: types.LAYER_EDIT_NO_DATA_LEGEND_SET,
            rest: { payload: true },
        },
        {
            creator: setUnclassifiedLegend,
            args: [true],
            type: types.LAYER_EDIT_UNCLASSIFIED_LEGEND_SET,
            rest: { payload: true },
        },
        {
            creator: setEarthEnginePeriod,
            args: [{ id: 'period1' }],
            type: types.LAYER_EDIT_EARTH_ENGINE_PERIOD_SET,
            rest: { payload: { id: 'period1' } },
        },
        {
            creator: setFeatureStyle,
            args: [{ color: '#fff' }],
            type: types.LAYER_EDIT_FEATURE_STYLE_SET,
            rest: { payload: { color: '#fff' } },
        },
        {
            creator: setLabelDataItem,
            args: [{ id: 'de1' }],
            type: types.LAYER_EDIT_LABEL_DATA_ITEM_ID_SET,
            rest: { item: { id: 'de1' } },
        },
    ])(
        '$creator.name creates the expected action',
        ({ creator, args, type, rest }) => {
            expect(creator(...args)).toEqual({
                type,
                ...rest,
            })
        }
    )
})

describe('setBand', () => {
    it('uses the id of the given band object', () => {
        expect(setBand({ id: 'B4' })).toEqual({
            type: types.LAYER_EDIT_BAND_SET,
            payload: 'B4',
        })
    })

    it('uses the value directly when not given an object', () => {
        expect(setBand('B4')).toEqual({
            type: types.LAYER_EDIT_BAND_SET,
            payload: 'B4',
        })
    })
})
