import fs from 'node:fs/promises'
import path from 'node:path'

const HOST_PAGE_ROUTE = '/plugin-host.html'
const HOST_PAGE_DIR = 'src/pluginHost'

// The /plugin-host.html page (src/pluginHost) is outside Vite's root
// (.d2/shell): the dev server serves it by hand, and builds only include it
// with BUILD_PLUGIN_HOST=true (PR previews), never in releases
const servePluginHost = () => ({
    name: 'maps:serve-plugin-host',
    apply: 'serve',
    configureServer(server) {
        server.middlewares.use((req, res, next) => {
            const [pathname] = (req.url ?? '').split('?')

            if (pathname !== HOST_PAGE_ROUTE) {
                next()
                return
            }

            const shellPath = path.resolve(HOST_PAGE_DIR, 'index.html')
            const entryPath = path.resolve(HOST_PAGE_DIR, 'main.jsx')

            fs.readFile(shellPath, 'utf8')
                .then((shell) =>
                    server.transformIndexHtml(
                        HOST_PAGE_ROUTE,
                        shell.replace('__ENTRY_MODULE__', `/@fs${entryPath}`)
                    )
                )
                .then((html) => {
                    res.statusCode = 200
                    res.setHeader('Content-Type', 'text/html')
                    res.end(html)
                })
                .catch(next)
        })
    },
})

const buildPluginHost = () => ({
    name: 'maps:build-plugin-host',
    apply: 'build',
    async config({ root }) {
        const pagePath = path.join(root, 'plugin-host.html')
        const entryPath = path.relative(
            root,
            path.resolve(HOST_PAGE_DIR, 'main.jsx')
        )
        const shell = await fs.readFile(
            path.resolve(HOST_PAGE_DIR, 'index.html'),
            'utf8'
        )
        await fs.writeFile(
            pagePath,
            shell
                .replace(
                    '<!DOCTYPE html>',
                    '<!DOCTYPE html>\n<!-- Generated by buildPluginHost (vite-extensions.config.mjs) from src/pluginHost/index.html -->'
                )
                .replace('__ENTRY_MODULE__', `./${entryPath}`)
        )
        return { build: { rollupOptions: { input: { pluginHost: pagePath } } } }
    },
})

export default {
    plugins: [
        servePluginHost(),
        process.env.BUILD_PLUGIN_HOST === 'true' && buildPluginHost(),
    ],
    optimizeDeps: {
        // Excluded so Vite serves maps-gl via /@fs/... with its full
        // transform pipeline, which lets the EE worker URL resolve to the
        // actual source file (rather than /.vite/earthengine/... where
        // bare imports are not rewritten).
        exclude: ['@dhis2/maps-gl'],
        // maps-gl's CJS deps must be listed explicitly; Vite's scanner
        // won't traverse an excluded package to discover them.
        include: [
            'maplibre-gl',
            'fetch-jsonp',
            'lodash.throttle',
            '@mapbox/sphericalmercator',
            '@turf/area',
            '@turf/bbox',
            '@turf/buffer',
            '@turf/center-of-mass',
            '@turf/centroid',
            '@turf/circle',
            '@turf/jsts',
            '@turf/length',
            'comlink',
            'concaveman',
            'polylabel',
            'pretty-bytes',
            'suggestions',
            'uuid',
        ],
        esbuildOptions: {
            target: 'es2022',
        },
    },
    build: {
        target: 'es2022',
        rollupOptions: {
            output: {
                manualChunks: {
                    'maps-gl': ['@dhis2/maps-gl'],
                },
            },
        },
    },
}
