/* MAP */
export const MAP_NEW = 'MAP_NEW'
export const MAP_SET = 'MAP_SET'
export const MAP_PROPS_SET = 'MAP_PROPS_SET'
export const MAP_CONTEXT_MENU_OPEN = 'MAP_CONTEXT_MENU_OPEN'
export const MAP_CONTEXT_MENU_CLOSE = 'MAP_CONTEXT_MENU_CLOSE'
export const MAP_COORDINATE_OPEN = 'MAP_COORDINATE_OPEN'
export const MAP_COORDINATE_CLOSE = 'MAP_COORDINATE_CLOSE'
export const MAP_EARTH_ENGINE_VALUE_SHOW = 'MAP_EARTH_ENGINE_VALUE_SHOW'
export const MAP_ALERTS_CLEAR = 'MAP_ALERT_CLEAR'

/* ORIGINAL MAP */
export const ORIGINAL_MAP_SET = 'ORIGINAL_MAP_SET'

/* BASEMAP */
export const BASEMAP_SELECTED = 'BASEMAP_SELECTED'
export const BASEMAP_TOGGLE_EXPAND = 'BASEMAP_TOGGLE_EXPAND'
export const BASEMAP_TOGGLE_VISIBILITY = 'BASEMAP_TOGGLE_VISIBILITY'
export const BASEMAP_CHANGE_OPACITY = 'BASEMAP_CHANGE_OPACITY'

/* LAYER */
export const LAYER_ADD = 'LAYER_ADD'
export const LAYER_REMOVE = 'LAYER_REMOVE'
export const LAYER_CHANGE_OPACITY = 'LAYER_CHANGE_OPACITY'
export const LAYER_EDIT = 'LAYER_EDIT'
export const LAYER_EDIT_SUCCESS = 'LAYER_EDIT_SUCCESS'
export const LAYER_CANCEL = 'LAYER_CANCEL'
export const LAYER_LOAD = 'LAYER_LOAD'
export const LAYER_LOAD_SUCCESS = 'LAYER_LOAD_SUCCESS'
export const LAYER_LOADING_SET = 'LAYER_LOADING_SET'
export const LAYER_SORT = 'LAYER_SORT'
export const LAYER_TOGGLE_EXPAND = 'LAYER_TOGGLE_EXPAND'
export const LAYER_TOGGLE_VISIBILITY = 'LAYER_TOGGLE_VISIBILITY'
export const LAYER_UPDATE = 'LAYER_UPDATE'
export const LAYER_DRILL = 'LAYER_DRILL'

/* DATA TABLE */
export const DATA_TABLE_CLOSE = 'DATA_TABLE_CLOSE'
export const DATA_TABLE_TOGGLE = 'DATA_TABLE_TOGGLE'
export const DATA_TABLE_RESIZE = 'DATA_TABLE_RESIZE'

/* DATA FILTER */
export const DATA_FILTER_SET = 'DATA_FILTER_SET'
export const DATA_FILTER_CLEAR = 'DATA_FILTER_CLEAR'

/* ORGANISATION UNITS */
export const ORGANISATION_UNIT_PROFILE_SET = 'ORGANISATION_UNIT_PROFILE_SET'
export const ORGANISATION_UNIT_PROFILE_CLOSE = 'ORGANISATION_UNIT_PROFILE_CLOSE'

/* USER INTERFACE */
export const LAYERS_PANEL_OPEN = 'LAYERS_PANEL_OPEN'
export const LAYERS_PANEL_CLOSE = 'LAYERS_PANEL_CLOSE'
export const INTERPRETATIONS_PANEL_OPEN = 'INTERPRETATIONS_PANEL_OPEN'
export const INTERPRETATIONS_PANEL_CLOSE = 'INTERPRETATIONS_PANEL_CLOSE'
export const LAYERS_SORTING_START = 'LAYERS_SORTING_START'
export const LAYERS_SORTING_END = 'LAYERS_SORTING_END'

/* LAYER EDIT */
export const LAYER_EDIT_PROGRAM_SET = 'LAYER_EDIT_PROGRAM_SET'
export const LAYER_EDIT_PROGRAM_STAGE_SET = 'LAYER_EDIT_PROGRAM_STAGE_SET'
export const LAYER_EDIT_PROGRAM_INDICATOR_SET =
    'LAYER_EDIT_PROGRAM_INDICATOR_SET'
export const LAYER_EDIT_PERIOD_NAME_SET = 'LAYER_EDIT_PERIOD_NAME_SET'
export const LAYER_EDIT_PERIOD_SET = 'LAYER_EDIT_PERIOD_SET'
export const LAYER_EDIT_PERIODS_SET = 'LAYER_EDIT_PERIODS_SET'
export const LAYER_EDIT_START_DATE_SET = 'LAYER_EDIT_START_DATE_SET'
export const LAYER_EDIT_BACKUP_PERIODSDATES_SET =
    'LAYER_EDIT_BACKUP_PERIODSDATES_SET'
export const LAYER_EDIT_END_DATE_SET = 'LAYER_EDIT_END_DATE_SET'
export const LAYER_EDIT_FILTER_ADD = 'LAYER_EDIT_FILTER_ADD'
export const LAYER_EDIT_FILTER_REMOVE = 'LAYER_EDIT_FILTER_REMOVE'
export const LAYER_EDIT_FILTER_CHANGE = 'LAYER_EDIT_FILTER_CHANGE'
export const LAYER_EDIT_DIMENSION_FILTER_ADD = 'LAYER_EDIT_DIMENSION_FILTER_ADD'
export const LAYER_EDIT_DIMENSION_FILTER_REMOVE =
    'LAYER_EDIT_DIMENSION_FILTER_REMOVE'
export const LAYER_EDIT_DIMENSION_FILTER_CHANGE =
    'LAYER_EDIT_DIMENSION_FILTER_CHANGE'
export const LAYER_EDIT_STYLE_DATA_ITEM_SET = 'LAYER_EDIT_STYLE_DATA_ITEM_SET'
export const LAYER_EDIT_STYLE_DATA_ITEM_OPTIONS_SET =
    'LAYER_EDIT_STYLE_DATA_ITEM_OPTIONS_SET'
export const LAYER_EDIT_STYLE_DATA_ITEM_BOOLEAN_SET =
    'LAYER_EDIT_STYLE_DATA_ITEM_BOOLEAN_SET'
export const LAYER_EDIT_THEMATIC_MAP_TYPE_SET =
    'LAYER_EDIT_THEMATIC_MAP_TYPE_SET'
export const LAYER_EDIT_CLASSIFICATION_SET = 'LAYER_EDIT_CLASSIFICATION_SET'
export const LAYER_EDIT_COLOR_SCALE_SET = 'LAYER_EDIT_COLOR_SCALE_SET'
export const LAYER_EDIT_DATA_ITEM_SET = 'LAYER_EDIT_DATA_ITEM_SET'
export const LAYER_EDIT_EVENT_STATUS_SET = 'LAYER_EDIT_EVENT_STATUS_SET'
export const LAYER_EDIT_EVENT_COORDINATE_FIELD_SET =
    'LAYER_EDIT_EVENT_COORDINATE_FIELD_SET'
export const LAYER_EDIT_EVENT_CLUSTERING_SET = 'LAYER_EDIT_EVENT_CLUSTERING_SET'
export const LAYER_EDIT_EVENT_POINT_RADIUS_SET =
    'LAYER_EDIT_EVENT_POINT_RADIUS_SET'
export const LAYER_EDIT_EVENT_POINT_COLOR_SET =
    'LAYER_EDIT_EVENT_POINT_COLOR_SET'
export const LAYER_EDIT_RELATED_POINT_COLOR_SET =
    'LAYER_EDIT_RELATED_POINT_COLOR_SET'
export const LAYER_EDIT_RELATED_POINT_RADIUS_SET =
    'LAYER_EDIT_RELATED_POINT_RADIUS_SET'
export const LAYER_EDIT_RELATIONSHIP_LINE_COLOR_SET =
    'LAYER_EDIT_RELATIONSHIP_LINE_COLOR_SET'
export const LAYER_EDIT_ORGANISATION_UNITS_SET =
    'LAYER_EDIT_ORGANISATION_UNITS_SET'
export const LAYER_EDIT_ORGANISATION_UNIT_GROUP_SET =
    'LAYER_EDIT_ORGANISATION_UNIT_GROUP_SET'
export const LAYER_EDIT_ORGANISATION_UNIT_MODE_SET =
    'LAYER_EDIT_ORGANISATION_UNIT_MODE_SET'
export const LAYER_EDIT_ORGANISATION_UNIT_COLOR_SET =
    'LAYER_EDIT_ORGANISATION_UNIT_COLOR_SET'
export const LAYER_EDIT_ORGANISATION_UNIT_FIELD_SET =
    'LAYER_EDIT_ORGANISATION_UNIT_FIELD_SET'
export const LAYER_EDIT_VALUE_TYPE_SET = 'LAYER_EDIT_VALUE_TYPE_SET'
export const LAYER_EDIT_INDICATOR_GROUP_SET = 'LAYER_EDIT_INDICATOR_GROUP_SET'
export const LAYER_EDIT_PERIOD_TYPE_SET = 'LAYER_EDIT_PERIOD_TYPE_SET'
export const LAYER_EDIT_RENDERING_STRATEGY_SET =
    'LAYER_EDIT_RENDERING_STRATEGY_SET'
export const LAYER_EDIT_AGGREGATION_TYPE_SET = 'LAYER_EDIT_AGGREGATION_TYPE_SET'
export const LAYER_EDIT_DATA_ELEMENT_GROUP_SET =
    'LAYER_EDIT_DATA_ELEMENT_GROUP_SET'
export const LAYER_EDIT_STYLE_SET = 'LAYER_EDIT_STYLE_SET'
export const LAYER_EDIT_FILTER_SET = 'LAYER_EDIT_FILTER_SET'
export const LAYER_EDIT_LABELS_SET = 'LAYER_EDIT_LABELS_SET'
export const LAYER_EDIT_LABEL_TEMPLATE = 'LAYER_EDIT_LABEL_TEMPLATE'
export const LAYER_EDIT_LABEL_FONT_SIZE_SET = 'LAYER_EDIT_LABEL_FONT_SIZE_SET'
export const LAYER_EDIT_LABEL_FONT_WEIGHT_SET =
    'LAYER_EDIT_LABEL_FONT_WEIGHT_SET'
export const LAYER_EDIT_LABEL_FONT_STYLE_SET = 'LAYER_EDIT_LABEL_FONT_STYLE_SET'
export const LAYER_EDIT_LABEL_FONT_COLOR_SET = 'LAYER_EDIT_LABEL_FONT_COLOR_SET'
export const LAYER_EDIT_BUFFER_RADIUS_SET = 'LAYER_EDIT_BUFFER_RADIUS_SET'
export const LAYER_EDIT_GEOMETRY_CENTROIDS_SET =
    'LAYER_EDIT_GEOMETRY_CENTROIDS_SET'
export const LAYER_EDIT_RADIUS_LOW_SET = 'LAYER_EDIT_RADIUS_LOW_SET'
export const LAYER_EDIT_RADIUS_HIGH_SET = 'LAYER_EDIT_RADIUS_HIGH_SET'
export const LAYER_EDIT_LEGEND_SET_SET = 'LAYER_EDIT_LEGEND_SET_SET'
export const LAYER_EDIT_ORGANISATION_UNIT_PATH_SET =
    'LAYER_EDIT_ORGANISATION_UNIT_PATH_SET' // Load organisation unit tree path (temporary solution, as favorites don't include paths)
export const LAYER_EDIT_ORGANISATION_UNIT_PATH_LOAD =
    'LAYER_EDIT_ORGANISATION_UNIT_PATH_LOAD' // Load organisation unit tree path (temporary solution, as favorites don't include paths)
export const LAYER_EDIT_OPERAND_SET = 'OPERAND_SET' // Data element operands (details)
export const LAYER_EDIT_TRACKED_ENTITY_TYPE_SET =
    'LAYER_EDIT_TRACKED_ENTITY_TYPE_SET'
export const LAYER_EDIT_TRACKED_ENTITY_RELATIONSHIP_TYPE_SET =
    'LAYER_EDIT_TRACKED_ENTITY_RELATIONSHIP_TYPE_SET'
export const LAYER_EDIT_TRACKED_ENTITY_RELATIONSHIP_OUTSIDE_PROGRAM_SET =
    'LAYER_EDIT_TRACKED_ENTITY_RELATIONSHIP_OUTSIDE_PROGRAM_SET'
export const LAYER_EDIT_PROGRAM_STATUS_SET = 'LAYER_EDIT_PROGRAM_STATUS_SET'
export const LAYER_EDIT_FOLLOW_UP_SET = 'LAYER_EDIT_FOLLOW_UP_SET'
export const LAYER_EDIT_NO_DATA_COLOR_SET = 'LAYER_EDIT_NO_DATA_COLOR_SET'
export const LAYER_EDIT_BAND_SET = 'LAYER_EDIT_BAND_SET'
export const LAYER_EDIT_FEATURE_STYLE_SET = 'LAYER_EDIT_FEATURE_STYLE_SET'
export const LAYER_EDIT_FALLBACK_COORDINATE_FIELD_SET =
    'LAYER_EDIT_FALLBACK_COORDINATE_FIELD_SET'
export const LAYER_EDIT_EARTH_ENGINE_PERIOD_SET =
    'LAYER_EDIT_EARTH_ENGINE_PERIOD_SET'

/* PERIODS */
export const RELATIVE_PERIODS_SET = 'RELATIVE_PERIODS_SET'
export const RELATIVE_PERIODS_TRANSLATE = 'RELATIVE_PERIODS_TRANSLATE'

/* INTERPRETATIONS */
export const INTERPRETATION_SET = 'INTERPRETATION_SET'

/* DOWNLOAD (PNG) */
export const DOWNLOAD_MODE_OPEN = 'DOWNLOAD_MODE_OPEN'
export const DOWNLOAD_MODE_CLOSE = 'DOWNLOAD_MODE_CLOSE'
export const DOWNLOAD_CONFIG_SET = 'DOWNLOAD_CONFIG_SET'

/* ANALYTICAL OBJECTS (BETWEEN APPS) */
export const ANALYTICAL_OBJECT_SET = 'ANALYTICAL_OBJECT_SET'
export const ANALYTICAL_OBJECT_CLEAR = 'ANALYTICAL_OBJECT_CLEAR'

/* FEATURE */
export const FEATURE_HIGHLIGHT = 'FEATURE_HIGHLIGHT'
export const FEATURE_PROFILE_SET = 'FEATURE_PROFILE_SET'
export const FEATURE_PROFILE_CLOSE = 'FEATURE_PROFILE_CLOSE'

/* AGGREGATIONS */
export const AGGREGATIONS_SET = 'AGGREGATIONS_SET'

/* LAYER SOURCES */
export const LAYER_SOURCES_INIT = 'LAYER_SOURCES_INIT'
export const LAYER_SOURCE_ADD = 'LAYER_SOURCE_ADD'
export const LAYER_SOURCE_REMOVE = 'LAYER_SOURCE_REMOVE'
