import { FALLBACK_BASEMAP_ID } from './basemaps.js'

export const apiVersion = 40

export const DEFAULT_SYSTEM_SETTINGS = {
    keyDefaultBaseMap: FALLBACK_BASEMAP_ID,
}

export const SYSTEM_SETTINGS_HIDE_DAILY_PERIODS = 'keyHideDailyPeriods'
export const SYSTEM_SETTINGS_HIDE_WEEKLY_PERIODS = 'keyHideWeeklyPeriods'
export const SYSTEM_SETTINGS_HIDE_BIWEEKLY_PERIODS = 'keyHideBiWeeklyPeriods'
export const SYSTEM_SETTINGS_HIDE_MONTHLY_PERIODS = 'keyHideMonthlyPeriods'
export const SYSTEM_SETTINGS_HIDE_BIMONTHLY_PERIODS = 'keyHideBiMonthlyPeriods'

export const SYSTEM_SETTINGS = [
    'keyAnalysisRelativePeriod',
    'keyBingMapsApiKey',
    SYSTEM_SETTINGS_HIDE_DAILY_PERIODS,
    SYSTEM_SETTINGS_HIDE_WEEKLY_PERIODS,
    SYSTEM_SETTINGS_HIDE_BIWEEKLY_PERIODS,
    SYSTEM_SETTINGS_HIDE_MONTHLY_PERIODS,
    SYSTEM_SETTINGS_HIDE_BIMONTHLY_PERIODS,
    'keyDefaultBaseMap',
]

export const MAPS_ADMIN_AUTHORITY_ID = 'F_EXTERNAL_MAP_LAYER_PUBLIC_ADD'

export const MAPS_APP_NAMESPACE = 'DHIS2_MAPS_APP_CORE'
export const MAPS_APP_KEY_MANAGED_LAYER_SOURCES = 'MANAGED_LAYER_SOURCES'
