export const ORIGIN = {
    EARTH_ENGINE: 'Earth Engine',
    STAC: 'STAC',
    COPERNICUS_CDS: 'Copernicus CDS',
    ARCGIS: 'ArcGIS',
    WMS: 'WMS',
    XYZ: 'XYZ / TMS',
    GEOJSON_URL: 'GeoJSON URL',
    ORG_DATA: 'Org data',
    USER_DATA: 'User data',
    SHARED_WITH_ME: 'Shared with me',
}

export const MAP_TYPE = {
    LAYER: 'layer',
    BASEMAP: 'basemap',
}

export const PERIOD_TYPE = {
    DAILY: 'Daily',
    WEEKLY: 'Weekly',
    MONTHLY: 'Monthly',
    ANNUAL: 'Annual',
    OTHER: 'Other',
}

export const RESOLUTION = {
    GLOBAL: 'Global',
    REGIONAL: 'Regional',
    LOCAL: 'Local',
}

export const mockCatalogueSources = [
    // Built-in basemaps — IDs match the real basemap IDs in basemaps.js
    {
        id: 'osmLight',
        name: 'OSM Light',
        description: 'Light CartoDB basemap built on OpenStreetMap data.',
        extendedDescription: null,
        img: 'images/osmlight.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'openstreetmap'],
        isFavorite: true,
        startYear: null,
        endYear: null,
        periodCovered: 'Continuously updated',
        spatialResolution: null,
        providerUrl: 'https://www.openstreetmap.org/copyright',
        license: 'ODbL 1.0',
    },
    {
        id: 'openStreetMap',
        name: 'OSM Detailed',
        description:
            'Standard OpenStreetMap tiles with full road and POI detail.',
        extendedDescription: null,
        img: 'images/osm.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'openstreetmap'],
        isFavorite: true,
        startYear: null,
        endYear: null,
        periodCovered: 'Continuously updated',
        spatialResolution: null,
        providerUrl: 'https://www.openstreetmap.org/copyright',
        license: 'ODbL 1.0',
    },
    {
        id: 'sentinel2eox',
        name: 'Sentinel-2 EOX',
        description:
            'Cloudless Sentinel-2 satellite imagery composite for the current year.',
        extendedDescription: null,
        img: 'images/s2eox.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.ANNUAL,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'satellite'],
        isFavorite: true,
        startYear: 2015,
        endYear: null,
        periodCovered: '2015 – present (annual composites)',
        spatialResolution: '10 m',
        providerUrl: 'https://s2maps.eu/',
        license: 'Copernicus Sentinel data terms',
    },
    {
        id: 'bingLight',
        name: 'Bing Road',
        description: 'Microsoft Bing road map in a light canvas style.',
        extendedDescription: null,
        img: 'images/bingroad.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'bing', 'road'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Continuously updated',
        spatialResolution: null,
        providerUrl: 'https://www.bing.com/maps',
        license: 'Microsoft Bing Maps terms',
    },
    {
        id: 'bingDark',
        name: 'Bing Dark',
        description: 'Microsoft Bing road map in a dark canvas style.',
        extendedDescription: null,
        img: 'images/bingdark.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'bing', 'dark'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Continuously updated',
        spatialResolution: null,
        providerUrl: 'https://www.bing.com/maps',
        license: 'Microsoft Bing Maps terms',
    },
    {
        id: 'bingAerial',
        name: 'Bing Aerial',
        description: 'Microsoft Bing aerial / satellite imagery.',
        extendedDescription: null,
        img: 'images/bingaerial.jpeg',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'bing', 'satellite'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Varies by region',
        spatialResolution: null,
        providerUrl: 'https://www.bing.com/maps',
        license: 'Microsoft Bing Maps terms',
    },
    {
        id: 'bingHybrid',
        name: 'Bing Aerial Labels',
        description: 'Microsoft Bing aerial imagery with road labels overlay.',
        extendedDescription: null,
        img: 'images/binghybrid.jpeg',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'bing', 'satellite'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Varies by region',
        spatialResolution: null,
        providerUrl: 'https://www.bing.com/maps',
        license: 'Microsoft Bing Maps terms',
    },
    {
        id: 'azureLight',
        name: 'Azure Road',
        description: 'Microsoft Azure Maps road basemap in light style.',
        extendedDescription: null,
        img: 'images/azureroad.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'azure', 'road'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Continuously updated',
        spatialResolution: null,
        providerUrl: 'https://azure.microsoft.com/en-us/products/azure-maps',
        license: 'Microsoft Azure Maps terms',
    },
    {
        id: 'azureDark',
        name: 'Azure Dark',
        description: 'Microsoft Azure Maps road basemap in dark style.',
        extendedDescription: null,
        img: 'images/azuredark.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'azure', 'dark'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Continuously updated',
        spatialResolution: null,
        providerUrl: 'https://azure.microsoft.com/en-us/products/azure-maps',
        license: 'Microsoft Azure Maps terms',
    },
    {
        id: 'azureAerial',
        name: 'Azure Aerial',
        description: 'Microsoft Azure Maps aerial imagery basemap.',
        extendedDescription: null,
        img: 'images/azureaerial.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'azure', 'satellite'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Varies by region',
        spatialResolution: null,
        providerUrl: 'https://azure.microsoft.com/en-us/products/azure-maps',
        license: 'Microsoft Azure Maps terms',
    },
    {
        id: 'azureHybrid',
        name: 'Azure Aerial Labels',
        description:
            'Microsoft Azure Maps aerial imagery with road labels overlay.',
        extendedDescription: null,
        img: 'images/azurehybrid.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'azure', 'satellite'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Varies by region',
        spatialResolution: null,
        providerUrl: 'https://azure.microsoft.com/en-us/products/azure-maps',
        license: 'Microsoft Azure Maps terms',
    },
    // Earth Engine — layers only
    {
        id: 'ee-population',
        name: 'Population Total',
        description:
            'Estimated number of people living in an area at ~100m resolution, annually updated.',
        extendedDescription:
            'WorldPop Global High Resolution Population Denominators provide gridded population counts adjusted to match UN national estimates. Both unconstrained (modelled) and constrained (building-footprint-informed) variants are available. Commonly used as denominators in health burden calculations and small-area demographic analyses.',
        img: 'images/population.png',
        origin: ORIGIN.EARTH_ENGINE,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.ANNUAL,
        resolution: RESOLUTION.GLOBAL,
        tags: ['population', 'global', 'annual'],
        isFavorite: true,
        startYear: 2000,
        endYear: null,
        periodCovered: '2000–present',
        spatialResolution: '~100m',
        providerUrl:
            'https://developers.google.com/earth-engine/datasets/catalog/WorldPop_GP_100m_pop',
        license: 'CC BY 4.0',
    },
    {
        id: 'ee-temperature',
        name: 'Temperature Monthly',
        description:
            'Average monthly 2m air temperature from ERA5-Land reanalysis at ~11km resolution.',
        extendedDescription:
            'ERA5-Land is a reanalysis dataset produced by ECMWF providing a consistent account of land surface variables from 1950 to the present at roughly 9km native resolution. Monthly aggregates of 2-metre air temperature are available globally. Widely used in climate impact studies, disease modelling, and agricultural assessments.',
        img: 'images/temperature.png',
        origin: ORIGIN.EARTH_ENGINE,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.MONTHLY,
        resolution: RESOLUTION.GLOBAL,
        tags: ['climate', 'temperature', 'monthly'],
        isFavorite: true,
        startYear: 1950,
        endYear: null,
        periodCovered: '1950–present',
        spatialResolution: '~11km',
        providerUrl:
            'https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_LAND_MONTHLY_AGGR',
        license: 'Copernicus License',
    },
    {
        id: 'ee-precipitation',
        name: 'Precipitation Monthly',
        description:
            'Monthly total precipitation from CHIRPS dataset at ~5km resolution.',
        extendedDescription:
            'CHIRPS blends satellite imagery with ground station observations to produce quasi-global rainfall estimates. Covers latitudes 50°S–50°N and is updated monthly with a ~3-week lag. Extensively used in food security, drought monitoring, and malaria transmission modelling.',
        img: 'images/precipitation.png',
        origin: ORIGIN.EARTH_ENGINE,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.MONTHLY,
        resolution: RESOLUTION.GLOBAL,
        tags: ['climate', 'precipitation', 'monthly'],
        isFavorite: true,
        startYear: 1981,
        endYear: null,
        periodCovered: '1981–present',
        spatialResolution: '~5km',
        providerUrl:
            'https://developers.google.com/earth-engine/datasets/catalog/UCSB-CHG_CHIRPS_MONTHLY',
        license: 'Public Domain (CC0)',
    },
    {
        id: 'ee-vegetation',
        name: 'Vegetation (NDVI)',
        description:
            'Normalized Difference Vegetation Index from MODIS at ~500m resolution.',
        extendedDescription:
            'The MOD13A1 product provides NDVI and EVI indices derived from MODIS Terra satellite observations as 16-day composites. Cloud contamination is minimised through temporal compositing. NDVI is widely used as a proxy for vegetation health, seasonal land cover change, and habitat suitability in epidemiological research.',
        img: 'images/vegetation.png',
        origin: ORIGIN.EARTH_ENGINE,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.MONTHLY,
        resolution: RESOLUTION.GLOBAL,
        tags: ['vegetation', 'ndvi', 'monthly'],
        isFavorite: true,
        startYear: 2000,
        endYear: null,
        periodCovered: '2000–present',
        spatialResolution: '~500m',
        providerUrl:
            'https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MOD13A1',
        license: 'Public Domain (CC0)',
    },
    {
        id: 'ee-elevation',
        name: 'Elevation (SRTM)',
        description:
            'Digital elevation model at ~30m resolution from the Shuttle Radar Topography Mission.',
        extendedDescription:
            'The SRTM DEM was acquired during an 11-day Space Shuttle mission in February 2000. It provides near-global coverage between 60°N and 56°S at 1 arc-second resolution. The dataset is static (single acquisition) and commonly used for terrain analysis, watershed delineation, and accessibility modelling.',
        img: 'images/elevation.png',
        origin: ORIGIN.EARTH_ENGINE,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['elevation', 'terrain', 'static'],
        isFavorite: true,
        startYear: 2000,
        endYear: 2000,
        periodCovered: 'February 2000 (static)',
        spatialResolution: '~30m',
        providerUrl:
            'https://developers.google.com/earth-engine/datasets/catalog/USGS_SRTMGL1_003',
        license: 'Public Domain (CC0)',
    },
    // STAC — layers only
    {
        id: 'stac-worldpop-total',
        name: 'WorldPop Global Mosaic 100m',
        description:
            'Global high-resolution population count grid at 100m, from the WorldPop STAC catalogue.',
        extendedDescription:
            'WorldPop produces gridded population estimates using a random forest model trained on census data, satellite imagery, and ancillary datasets. The global mosaic tiles are served via a STAC-compliant endpoint at worldpop.data.gov.uk, enabling direct COG access per country and year. Both total and age/sex disaggregated variants are available.',
        img: 'images/population.png',
        origin: ORIGIN.STAC,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.ANNUAL,
        resolution: RESOLUTION.GLOBAL,
        tags: ['population', 'worldpop', 'global', 'stac'],
        isFavorite: true,
        stacEndpoint: 'https://worldpop.data.gov.uk/stac',
        startYear: 2000,
        endYear: 2020,
        periodCovered: '2000–2020',
        spatialResolution: '~100m',
        providerUrl: 'https://www.worldpop.org',
        license: 'CC BY 4.0',
    },
    {
        id: 'stac-worldpop-agesex',
        name: 'WorldPop Age & Sex Structure 2020',
        description:
            'Population disaggregated by age group and sex at 100m grid level for the year 2020.',
        extendedDescription:
            'Separate rasters for 5-year age groups (0–4, 5–9, …, 80+) split by male and female for each country. Particularly useful for computing age-standardised incidence rates or modelling burden of age-specific diseases such as malaria in children under five.',
        img: 'images/population.png',
        origin: ORIGIN.STAC,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.ANNUAL,
        resolution: RESOLUTION.GLOBAL,
        tags: ['population', 'worldpop', 'age-sex', 'demographics', 'stac'],
        isFavorite: false,
        stacEndpoint: 'https://worldpop.data.gov.uk/stac',
        startYear: 2020,
        endYear: 2020,
        periodCovered: '2020 (single year)',
        spatialResolution: '~100m',
        providerUrl: 'https://www.worldpop.org',
        license: 'CC BY 4.0',
    },
    {
        id: 'stac-sentinel2',
        name: 'Sentinel-2 Imagery',
        description:
            'Multi-spectral optical satellite imagery at 10m resolution from the ESA Copernicus programme.',
        extendedDescription:
            'Sentinel-2 (S2A and S2B) provides 13-band multispectral imagery with a 5-day revisit time. Level-2A (surface reflectance) scenes are available via STAC on AWS. Bands range from 10m (visible, NIR) to 60m (coastal aerosol, SWIR cirrus). Suitable for land cover mapping, flood extent mapping, and crop monitoring.',
        img: 'images/s2eox.png',
        origin: ORIGIN.STAC,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.DAILY,
        resolution: RESOLUTION.REGIONAL,
        tags: ['satellite', 'imagery', 'optical', 'copernicus', 'stac'],
        isFavorite: false,
        startYear: 2015,
        endYear: null,
        periodCovered: '2015–present',
        spatialResolution: '10–60m (band dependent)',
        providerUrl: 'https://registry.opendata.aws/sentinel-2/',
        license: 'Copernicus Sentinel Data Terms',
    },
    // Copernicus CDS — layers only
    {
        id: 'cds-era5-temperature',
        name: 'ERA5 Reanalysis Temperature',
        description:
            'Global climate reanalysis providing hourly and monthly temperature back to 1940 at ~31km resolution.',
        extendedDescription:
            'ERA5 is the fifth generation ECMWF atmospheric reanalysis. It assimilates vast amounts of historical observations into a consistent model output and provides uncertainty estimates alongside central values. Accessed via the Copernicus Climate Data Store API.',
        img: 'images/temperature.png',
        origin: ORIGIN.COPERNICUS_CDS,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.MONTHLY,
        resolution: RESOLUTION.GLOBAL,
        tags: ['climate', 'temperature', 'era5', 'reanalysis'],
        isFavorite: true,
        startYear: 1940,
        endYear: null,
        periodCovered: '1940–present',
        spatialResolution: '~31km',
        providerUrl:
            'https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land-monthly-means',
        license: 'Copernicus License',
    },
    {
        id: 'cds-era5-precipitation',
        name: 'ERA5 Total Precipitation',
        description:
            'Accumulated liquid and frozen water from ERA5, including rain and snow at ~31km resolution.',
        extendedDescription:
            'ERA5 total precipitation is the sum of large-scale and convective precipitation expressed as depth of water per grid cell. Monthly accumulations are available globally from 1940. Preferable to CHIRPS for polar regions or areas with sparse rain gauge networks.',
        img: 'images/precipitation.png',
        origin: ORIGIN.COPERNICUS_CDS,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.MONTHLY,
        resolution: RESOLUTION.GLOBAL,
        tags: ['climate', 'precipitation', 'era5', 'reanalysis'],
        isFavorite: false,
        startYear: 1940,
        endYear: null,
        periodCovered: '1940–present',
        spatialResolution: '~31km',
        providerUrl:
            'https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land-monthly-means',
        license: 'Copernicus License',
    },
    // ArcGIS — mixed
    {
        id: 'arcgis-boundaries',
        name: 'Administrative Boundaries',
        description:
            'Country and sub-national administrative boundaries from ArcGIS Living Atlas of the World.',
        extendedDescription:
            'Multi-level administrative boundaries (country, province, district) sourced from national mapping agencies and harmonised globally. Attribute data includes ISO codes, population estimates, and area statistics. Accessible via ArcGIS REST API as a vector feature service.',
        img: 'images/featurelayer.png',
        origin: ORIGIN.ARCGIS,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['boundaries', 'administrative', 'arcgis'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Updated annually',
        spatialResolution: null,
        providerUrl:
            'https://www.arcgis.com/home/item.html?id=2b93b06dc0dc4e809d3c8db5cb96ba69',
        license: 'Esri Master License Agreement',
    },
    {
        id: 'arcgis-roads',
        name: 'Road Network Basemap',
        description:
            'Global road network basemap tiles from ArcGIS Living Atlas, suitable as a background map.',
        extendedDescription:
            'Pre-rendered basemap tile service combining OpenStreetMap road data with Esri cartographic styling. Tiles are cached at zoom levels 0–19 for most regions. Supports both WMTS and XYZ tile access patterns.',
        img: 'images/featurelayer.png',
        origin: ORIGIN.ARCGIS,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['roads', 'transport', 'basemap', 'arcgis'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Updated quarterly',
        spatialResolution: null,
        providerUrl:
            'https://www.arcgis.com/home/item.html?id=de26a3cf4cc9451298ea173c4b324736',
        license: 'Esri Master License Agreement',
    },
    // WMS — mixed
    {
        id: 'wms-osm',
        name: 'OpenStreetMap WMS',
        description:
            'OpenStreetMap rendered tiles served via WMS, suitable as a background basemap.',
        extendedDescription:
            'OpenStreetMap is a collaborative, freely editable map of the world maintained by a global volunteer community. This WMS endpoint serves Mapnik-rendered raster tiles. The ODbL license requires attribution and share-alike for derivative works.',
        img: 'images/osm.png',
        origin: ORIGIN.WMS,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'openstreetmap', 'wms'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'Continuously updated',
        spatialResolution: null,
        providerUrl: 'https://www.openstreetmap.org/copyright',
        license: 'ODbL 1.0',
    },
    {
        id: 'wms-health-facilities',
        name: 'National Health Facilities WMS',
        description:
            'Health facility locations and service areas served via WMS from the national GIS portal.',
        extendedDescription:
            'Published by the national Ministry of Health GIS unit, providing point locations for all registered health facilities along with service area polygons. Attributes include facility type, ownership, functional status, and catchment population.',
        img: 'images/facilities.png',
        origin: ORIGIN.WMS,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.LOCAL,
        tags: ['health', 'facilities', 'wms', 'national'],
        isFavorite: true,
        startYear: 2024,
        endYear: 2024,
        periodCovered: '2024',
        spatialResolution: null,
        providerUrl: null,
        license: 'Internal use only',
    },
    // XYZ / TMS — basemaps
    {
        id: 'xyz-satellite',
        name: 'Custom Satellite Basemap',
        description:
            'High-resolution satellite imagery tiles in XYZ/TMS format from a custom tile server.',
        extendedDescription:
            'Custom XYZ tile service hosting recent high-resolution satellite imagery for the region of interest. Available at zoom levels 0–17; native imagery resolution is approximately 50cm at the highest zoom.',
        img: 'images/s2eox.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.REGIONAL,
        tags: ['basemap', 'satellite', 'xyz'],
        isFavorite: false,
        startYear: 2024,
        endYear: null,
        periodCovered: '2024',
        spatialResolution: '~50cm (native)',
        providerUrl: null,
        license: 'Custom',
    },
    {
        id: 'xyz-terrain',
        name: 'Terrain Basemap',
        description:
            'Shaded relief terrain tiles showing elevation and topography as a background map.',
        extendedDescription:
            'Hillshade and contour-based terrain tiles generated from SRTM 30m elevation data using multi-directional shading. Available globally from zoom 0 to 14.',
        img: 'images/terrain.png',
        origin: ORIGIN.XYZ,
        mapType: MAP_TYPE.BASEMAP,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.GLOBAL,
        tags: ['basemap', 'terrain', 'elevation', 'xyz'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: 'February 2000 (static source)',
        spatialResolution: '~30m (source)',
        providerUrl: null,
        license: 'Custom',
    },
    // GeoJSON URL — layers only
    {
        id: 'geojson-districts',
        name: 'District Boundaries',
        description:
            'District-level administrative boundaries as GeoJSON served from the national data portal.',
        extendedDescription:
            'District polygons published by the national statistics office. Includes district codes, names, and regional groupings. Served with CORS headers; can be consumed directly by the Maps app without a proxy.',
        img: 'images/orgunits.png',
        origin: ORIGIN.GEOJSON_URL,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.LOCAL,
        tags: ['boundaries', 'districts', 'geojson'],
        isFavorite: false,
        startYear: 2024,
        endYear: 2024,
        periodCovered: '2024',
        spatialResolution: null,
        providerUrl: null,
        license: 'Open Government License',
    },
    {
        id: 'geojson-catchment',
        name: 'Health Catchment Areas',
        description:
            'Catchment area polygons for all registered health facilities, updated quarterly.',
        extendedDescription:
            'Service area polygons derived from Voronoi tessellation adjusted for road network travel times. Each polygon carries attributes for facility ID, name, estimated catchment population, and date of last revision.',
        img: 'images/thematic.png',
        origin: ORIGIN.GEOJSON_URL,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.LOCAL,
        tags: ['health', 'catchment', 'geojson'],
        isFavorite: false,
        startYear: 2024,
        endYear: 2024,
        periodCovered: 'Q2 2024',
        spatialResolution: null,
        providerUrl: null,
        license: 'Internal',
    },
    // Org / User data — layers only
    {
        id: 'org-drawn-polygons',
        name: 'Drawn Polygon Set',
        description:
            'Custom polygon areas drawn in the Maps app and saved to the organisation data store.',
        extendedDescription:
            'Manually digitised polygons created using the Maps app drawing tool and persisted in the DHIS2 organisation data store. These areas represent custom operational zones that do not correspond to official administrative boundaries.',
        img: 'images/thematic.png',
        origin: ORIGIN.ORG_DATA,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.LOCAL,
        tags: ['custom', 'drawn', 'org-data'],
        isFavorite: false,
        startYear: null,
        endYear: null,
        periodCovered: null,
        spatialResolution: null,
        providerUrl: null,
        license: null,
    },
    {
        id: 'org-health-zones',
        name: 'Uploaded Health Zones',
        description:
            'Health zone boundaries uploaded as GeoJSON and stored in the organisation data store.',
        extendedDescription:
            'GeoJSON boundaries uploaded by the GIS team to represent operational health zones used for programme planning. Zones do not align with administrative districts and reflect programme-specific catchment logic.',
        img: 'images/thematic.png',
        origin: ORIGIN.ORG_DATA,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.LOCAL,
        tags: ['health', 'zones', 'uploaded', 'org-data'],
        isFavorite: false,
        startYear: 2023,
        endYear: 2023,
        periodCovered: '2023',
        spatialResolution: null,
        providerUrl: null,
        license: null,
    },
    // Shared with me
    {
        id: 'shared-catchment-areas',
        name: 'District Catchment Areas',
        description:
            'Custom catchment polygons shared by Alice Smith — GIS team.',
        extendedDescription:
            'Service area polygons derived from road network travel times. Shared for use in the national malaria programme analysis. Contact Alice Smith (GIS team) for updates.',
        img: 'images/thematic.png',
        origin: ORIGIN.SHARED_WITH_ME,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.LOCAL,
        tags: ['health', 'catchment', 'shared'],
        isFavorite: false,
        startYear: 2024,
        endYear: 2024,
        periodCovered: 'Jun 2024',
        spatialResolution: null,
        providerUrl: null,
        license: null,
        sharedBy: 'Alice Smith',
    },
    {
        id: 'shared-vaccination-zones',
        name: 'Vaccination Coverage Zones',
        description:
            'Operational zones for the 2024 vaccination campaign, shared by Mohammed Al-Hassan.',
        extendedDescription:
            'Campaign-specific operational zones used to track vaccination coverage and identify unreached populations. Shared for cross-programme analysis. Contact the national immunisation team for the latest version.',
        img: 'images/thematic.png',
        origin: ORIGIN.SHARED_WITH_ME,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.LOCAL,
        tags: ['health', 'vaccination', 'shared'],
        isFavorite: false,
        startYear: 2024,
        endYear: 2024,
        periodCovered: 'Jul 2024',
        spatialResolution: null,
        providerUrl: null,
        license: null,
        sharedBy: 'Mohammed Al-Hassan',
    },
    {
        id: 'shared-custom-boundaries',
        name: 'Custom Admin Boundaries 2024',
        description:
            'Updated administrative boundaries shared by the GIS Team — includes boundary revisions.',
        extendedDescription:
            'Revised district boundaries reflecting the 2024 administrative reorganisation. Shared by the national GIS team pending official publication. Not to be used for official reporting until gazetted.',
        img: 'images/orgunits.png',
        origin: ORIGIN.SHARED_WITH_ME,
        mapType: MAP_TYPE.LAYER,
        periodType: PERIOD_TYPE.OTHER,
        resolution: RESOLUTION.LOCAL,
        tags: ['boundaries', 'administrative', 'shared'],
        isFavorite: false,
        startYear: 2024,
        endYear: 2024,
        periodCovered: 'Aug 2024',
        spatialResolution: null,
        providerUrl: null,
        license: null,
        sharedBy: 'GIS Team',
    },
]
