name: 'publish build to d2-ci'

on:
    push:
        branches:
            - master
        tags:
            - '*'

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
    CI: true

jobs:
    echo-conditions:
        runs-on: ubuntu-latest
        steps:
            - name: Check and Echo Conditions
              run: |
                  # Extract values from the GitHub context
                  FORK_REPOSITORY=${{ github.event.push.repository.fork }}
                  GITHUB_REF=${{ github.ref }}
                  COMMIT_MESSAGE="${{ github.event.head_commit.message }}"

                  # Condition 1: Check if the repository is not a fork
                  CONDITION_1=$((! FORK_REPOSITORY))
                  echo "Condition 1 (Not a fork): $CONDITION_1"

                  # Condition 2: Check if the reference starts with 'refs/tags/'
                  if [[ "$GITHUB_REF" == refs/tags/* ]]; then
                      CONDITION_2=true
                  else
                        CONDITION_2=false
                  fi
                  echo "Condition 2 (Starts with 'refs/tags/'): $CONDITION_2"

                  # Condition 3: Check if the reference is 'refs/heads/master' and commit message contains '[skip release]'
                  if [[ "$GITHUB_REF" == "refs/heads/master" && "$COMMIT_MESSAGE" == *"[skip release]"* ]]; then
                      CONDITION_3=true
                  else
                      CONDITION_3=false
                  fi
                    echo "Condition 3 (Is 'refs/heads/master' and contains '[skip release]'): $CONDITION_3"

                  # Combine conditions
                  FINAL_CONDITION=$((CONDITION_1 && (CONDITION_2 || CONDITION_3)))
                  echo "Final Condition: $FINAL_CONDITION"

    publish-to-d2-ci:
        if: |
            ${{ !github.event.push.repository.fork }} &&
            ${{ startsWith(github.ref, 'refs/tags/') || (github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[skip release]')) }}

        runs-on: ubuntu-latest
        steps:
            - name: Print GitHub event context
              run: echo "$GITHUB_EVENT" | jq '.'
              env:
                  GITHUB_EVENT: ${{ toJson(github.event) }}

            - name: Print GitHub ref
              run: echo "GITHUB_REF is $GITHUB_REF"

            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn d2-app-scripts build

            - name: Copy build to d2-ci
              uses: dhis2/deploy-build@master
              with:
                  build-dir: build/app
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

    report-deploy-failure:
        runs-on: ubuntu-latest
        needs: publish-to-d2-ci
        if: ${{ failure() && !cancelled() }}
        steps:
            - name: Send failure message to analytics-internal-bot slack channel
              id: slack_publish_failure
              uses: slackapi/slack-github-action@v1.23.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  payload: |
                      {
                          "text": ":small_red_triangle_down: :maps-app: Maps failed to deploy to d2-ci",
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
